# Lab 1.01 - Australian Athletes (ais)

In the Python cell below this one, paste all the imports you need for data analysis from the code examples (Numpy, Pandas, etc.).

In [23]:
# Importing the necessary packages
import numpy as np                                  # Scientific computing
import scipy.stats as stats                         # Statistical tests
import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype
import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation

Declare a variable `ais` and use it to import the dataset from the CSV-file `ais.csv` in [the directory `data/`](https://github.com/HoGentTIN/dsai-en-labs/tree/main/data) of the [Github repository](https://github.com/HoGentTIN/dsai-en-labs/) for the lab assignments. You can import a dataset with a URL pointing to the raw contents of the CSV-file in the Github repository (see the code example!).

This dataset contains 202 observations of Australian athletes with a variety of blood values. You can find the codebook (i.e., the explanation of what each variable/column in the dataset means) in [data/ais.md](https://github.com/HoGentTIN/dsai-en-labs/blob/main/data/ais.md). Show the first few observations of this sample.

In [31]:
ais = pd.read_csv("../data/ais.csv")

ais.head()

,id,rcc,wcc,hc,hg,ferr,bmi,ssf,pcBfat,lbm,ht,wt,sex,sport
0,1,3.96,7.5,37.5,12.3,60,20.56,109.1,19.75,63.32,195.9,78.9,f,B_Ball
1,2,4.41,8.3,38.2,12.7,68,20.67,102.8,21.30,58.55,189.7,74.4,f,B_Ball
2,3,4.14,5.0,36.4,11.6,21,21.86,104.6,19.88,55.36,177.8,69.1,f,B_Ball
3,4,4.11,5.3,37.3,12.6,69,21.88,126.4,23.66,57.18,185.0,74.9,f,B_Ball
4,5,4.45,6.8,41.5,14.0,29,18.96,80.3,17.64,53.20,184.6,64.6,f,B_Ball

Get general information about this dataset:

- How many rows and columns does the dataset have?
- Show general information about each variable, specifically the number of empty fields and the type of each variable (e.g., int64, float64, object)
- How many columns of each type are there?
- What is the measurement level (nominal, ordinal, interval, ratio) of each variable?

In [32]:
print(f"rows, columns: {ais.shape}")

print("*"*50)
print(ais.info())

print("*"*50)
print(ais.dtypes.value_counts)


# rcc       ratio
# wcc       ratio
# hc        ratio
# hg        ratio
# ferr      ratio
# bmi       ratio
# ssf       ratio
# pcBfat    ratio
# lbm       ratio
# ht        ratio
# wt        ratio
# sex       nominaal        Categorisch, geen volgorde
# sport     nominaal        Categorisch, geen volgorde

rows, columns: (202, 14)
**************************************************
<class 'pandas.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      202 non-null    int64
 1   rcc     202 non-null    float64
 2   wcc     202 non-null    float64
 3   hc      202 non-null    float64
 4   hg      202 non-null    float64
 5   ferr    202 non-null    int64
 6   bmi     202 non-null    float64
 7   ssf     202 non-null    float64
 8   pcBfat  202 non-null    float64
 9   lbm     202 non-null    float64
 10  ht      202 non-null    float64
 11  wt      202 non-null    float64
 12  sex     202 non-null    str
 13  sport   202 non-null    str
dtypes: float64(10), int64(2), str(2)
memory usage: 22.2 KB
None
**************************************************
<bound method IndexOpsMixin.value_counts of id          int64
rcc       float64
wcc       float64
hc        float64
hg        float64
ferr        int64
bmi       float64
ssf       float64
pcBfat    float64
lbm       float64
ht        float64
wt        float64
sex           str
sport         str
dtype: object>

The column "id" is not an actual variable, but an index. Mark it as such.

In [36]:
ais.set_index(['id'], inplace=True)

# Opnieuw toewijzen:
# - Nieuwe variable
# - inplace=True

The variables that are now considered "str" are qualitative variables. Change the type of each of these variables to "category". For ordinal variables, also define a type and impose an order. Verify that the conversion was successful by requesting info about the types again.

In [34]:
# Mark str variables
ais.sex = ais.sex.astype('category')

ais.sport = ais.sport.astype('category')

print("*"*50)
print(ais.dtypes)

**************************************************
id           int64
rcc        float64
wcc        float64
hc         float64
hg         float64
ferr         int64
bmi        float64
ssf        float64
pcBfat     float64
lbm        float64
ht         float64
wt         float64
sex       category
sport     category
dtype: object

Describe the columns `ferr`, `bmi`, `sex` and `sport` and the unique values in each of these columns. Do you recognize the characteristics of qualitative and quantitative variables in the result?

In [35]:
print(ais.ferr.describe())
print("*"*50)
print(ais.bmi.describe())
print("*"*50)
print(ais.sex.describe())
print("*"*50)
print(ais.sport.describe())

count    202.000000
mean      76.876238
std       47.501239
min        8.000000
25%       41.250000
50%       65.500000
75%       97.000000
max      234.000000
Name: ferr, dtype: float64
**************************************************
count    202.000000
mean      22.955891
std        2.863933
min       16.750000
25%       21.082500
50%       22.720000
75%       24.465000
max       34.420000
Name: bmi, dtype: float64
**************************************************
count     202
unique      2
top         m
freq      102
Name: sex, dtype: object
**************************************************
count     202
unique     10
top       Row
freq       37
Name: sport, dtype: object

Select following elements from the dataset:

- the second row (ids = 2)
- rows 4 to 6 (ids = 5 to 7)
- Columns 6 to 8 (`ferr`, `bmi`, `ssf`)
- the variable `pcBfat` (by name!). There are multiple ways to retrieve this!
- all observations for the sport "Netball"
- just the variable `wt` of the observations for "Netball"
- which sports are played by athletes with a BMI higher than 26? Also, provide a list of the unique values and a frequency table of how often each sport occurs.

In [47]:
ais.iloc[2]

rcc         4.14
wcc          5.0
hc          36.4
hg          11.6
ferr          21
bmi        21.86
ssf        104.6
pcBfat     19.88
lbm        55.36
ht         177.8
wt          69.1
sex            f
sport     B_Ball
Name: 3, dtype: object

In [48]:
ais.iloc[3:6]

,rcc,wcc,hc,hg,ferr,bmi,ssf,pcBfat,lbm,ht,wt,sex,sport
id,,,,,,,,,,,,,
4,4.11,5.3,37.3,12.6,69,21.88,126.4,23.66,57.18,185.0,74.9,f,B_Ball
5,4.45,6.8,41.5,14.0,29,18.96,80.3,17.64,53.20,184.6,64.6,f,B_Ball
6,4.10,4.4,37.4,12.5,42,21.04,75.2,15.58,53.77,174.0,63.7,f,B_Ball

In [49]:
ais[['ferr', 'bmi', 'ssf']]

     ferr    bmi    ssf
id
1      60  20.56  109.1
2      68  20.67  102.8
3      21  21.86  104.6
4      69  21.88  126.4
5      29  18.96   80.3
..    ...    ...    ...
198    90  27.56   67.2
199    38  23.76   56.5
200   122  22.01   47.6
201   233  22.34   60.4
202    32  21.07   34.9

[202 rows x 3 columns]

In [51]:
ais.iloc[:,4:7]

     ferr    bmi    ssf
id
1      60  20.56  109.1
2      68  20.67  102.8
3      21  21.86  104.6
4      69  21.88  126.4
5      29  18.96   80.3
..    ...    ...    ...
198    90  27.56   67.2
199    38  23.76   56.5
200   122  22.01   47.6
201   233  22.34   60.4
202    32  21.07   34.9

[202 rows x 3 columns]

In [52]:
ais.pcBfat

id
1      19.75
2      21.30
3      19.88
4      23.66
5      17.64
       ...
198    11.79
199    10.05
200     8.51
201    11.50
202     6.26
Name: pcBfat, Length: 202, dtype: float64

In [54]:
ais[ais['sport'] == 'Netball']

,rcc,wcc,hc,hg,ferr,bmi,ssf,pcBfat,lbm,ht,wt,sex,sport
id,,,,,,,,,,,,,
36,4.56,13.3,42.2,13.6,20,19.16,49.0,11.29,53.14,176.8,59.9,f,Netball
37,4.15,6.0,38.0,12.7,59,21.15,110.2,25.26,47.09,172.6,63.0,f,Netball
38,4.16,7.6,37.5,12.3,22,21.40,89.0,19.39,53.44,176.0,66.3,f,Netball
39,4.32,6.4,37.7,12.3,30,21.03,98.3,19.63,48.78,169.9,60.7,f,Netball
40,4.06,5.8,38.7,12.8,78,21.77,122.1,23.11,56.05,183.0,72.9,f,Netball
41,4.12,6.1,36.6,11.8,21,21.38,90.4,16.86,56.45,178.2,67.9,f,Netball
42,4.17,5.0,37.4,12.7,109,21.47,106.9,21.32,53.11,177.3,67.5,f,Netball
43,3.80,6.6,36.5,12.4,102,24.45,156.6,26.57,54.41,174.1,74.1,f,Netball
44,3.96,5.5,36.3,12.4,71,22.63,101.1,17.93,55.97,173.6,68.2,f,Netball
45,4.44,9.7,41.4,14.1,64,22.80,126.4,24.97,51.62,173.7,68.8,f,Netball
46,4.27,10.6,37.7,12.5,68,23.58,114.0,22.62,58.27,178.7,75.3,f,Netball
47,3.90,6.3,35.9,12.1,78,20.06,70.0,15.01,57.28,183.3,67.4,f,Netball
48,4.02,9.1,37.7,12.7,107,23.01,77.0,18.14,57.30,174.4,70.0,f,Netball
49,4.39,9.6,38.3,12.5,39,24.64,148.9,26.78,54.18,173.3,74.0,f,Netball
50,4.52,5.1,38.8,13.1,58,18.26,80.1,17.22,42.96,168.6,51.9,f,Netball
51,4.25,10.7,39.5,13.2,127,24.47,156.6,26.50,54.46,174.0,74.1,f,Netball
52,4.46,10.9,39.7,13.7,102,23.99,115.9,23.01,57.20,176.0,74.3,f,Netball
53,4.40,9.3,40.4,13.6,86,26.24,181.7,30.10,54.38,172.2,77.8,f,Netball
54,4.83,8.4,41.8,13.4,40,20.04,71.6,13.93,57.58,182.7,66.9,f,Netball
55,4.23,6.9,38.3,12.6,50,25.72,143.5,26.65,61.46,180.5,83.8,f,Netball
56,4.24,8.4,37.6,12.5,58,25.64,200.8,35.52,53.46,179.8,82.9,f,Netball
57,3.95,6.6,38.4,12.8,33,19.87,68.9,15.59,54.11,179.6,64.1,f,Netball
58,4.03,8.5,37.7,13.0,51,23.35,103.6,19.61,55.35,171.7,68.8,f,Netball

In [55]:
ais[ais['sport'] == 'Netball']['wt']

id
36    59.9
37    63.0
38    66.3
39    60.7
40    72.9
41    67.9
42    67.5
43    74.1
44    68.2
45    68.8
46    75.3
47    67.4
48    70.0
49    74.0
50    51.9
51    74.1
52    74.3
53    77.8
54    66.9
55    83.8
56    82.9
57    64.1
58    68.8
Name: wt, dtype: float64

In [60]:
print(ais['sport'][ais.bmi > 26])

print('*'*50)

print(ais['sport'][ais.bmi > 26].unique())

print('*'*50)

print(ais['sport'][ais.bmi > 26].value_counts())

id
53     Netball
70       Field
71       Field
72       Field
73       Field
75       Field
110       Swim
113       Swim
122        Row
125        Row
145      Field
146      Field
160      Field
162      Field
163      Field
176    T_Sprnt
178      Field
179      Field
192     W_Polo
196     W_Polo
198     W_Polo
Name: sport, dtype: category
Categories (10, str): ['B_Ball', 'Field', 'Gym', 'Netball', ..., 'T_400m', 'T_Sprnt', 'Tennis', 'W_Polo']
**************************************************
['Netball', 'Field', 'Swim', 'Row', 'T_Sprnt', 'W_Polo']
Categories (10, str): ['B_Ball', 'Field', 'Gym', 'Netball', ..., 'T_400m', 'T_Sprnt', 'Tennis', 'W_Polo']
**************************************************
sport
Field      12
W_Polo      3
Row         2
Swim        2
Netball     1
T_Sprnt     1
B_Ball      0
Gym         0
T_400m      0
Tennis      0
Name: count, dtype: int64