## Example Exam Questions Chapter 4

In [1]:
# Importing the necessary packages
import numpy as np                                  # Scientific computing
import scipy.stats as stats                         # Statistical tests
import pandas as pd                                 # Data Frame
from pandas.api.types import CategoricalDtype
import matplotlib.pyplot as plt                     # Basic visualisation
from statsmodels.graphics.mosaicplot import mosaic  # Mosaic diagram
import seaborn as sns                               # Advanced data visualisation

## Exercise 1
Criminologists have long debated whether there is a relationship between weather conditions and the number of crimes committed. In 1988, an article “Is there a
Season for Homicide?” (Criminology, 1988: 287-296) classified 1361 homicides by season, resulting
in the data below.  
Is there an association between season and the number of murders committed?

In [2]:
dfmurders = pd.DataFrame(data={
    'season': ['winter', 'spring','summer','autumn'],
    'number_of_murders': [328, 334, 372, 327]
})

In [ ]:
# Stap 1
# H₀ => geen verband tussen seizoenen en moorden
# H₁ => wel verband

# Stap 2
alpha = 0.05

# Stap 3
# => chi²

# Stap 4
# => p + g

observed = dfmurders['number_of_murders']
expected_p = np.array([0.25, 0.25, 0.25, 0.25])

n = sum(observed)          # Sample size
k = len(observed)          # Number of categories
dof = k - 1                # Degrees of freedom
expected = expected_p * n  # Expected absolute frequencies in the sample
g = stats.chi2.isf(alpha, df=dof)  # Critical value

# Goodness-of-fit-test in Python:
chi2, p = stats.chisquare(f_obs=observed, f_exp=expected)

print("Significance level  ⍺ = %.2f" % alpha)
print("Sample size         n = %d" % n)
print("k = %d; df = %d" % (k, dof))
print("Chi-squared        χ² = %.4f" % chi2)
print("Critical value      g = %.4f" % g)
print("p-value             p = %.4f" % p)

# Stap 5
# p >> alpha => Geen verband
# chi2 << g  |

Significance level  ⍺ = 0.05
Sample size         n = 1361
k = 4; df = 3
Chi-squared        χ² = 4.0345
Critical value      g = 7.8147
p-value             p = 0.2578

## Exercise 2
A random sample of individuals was taken, and each individual was classified according to their level of education and their sense of spirituality.
Is there an association between the level of education and the sense of spirituality?

In [7]:
dfspirituality = pd.DataFrame(data={
    'sense_of_spirituality': ['lot', 'moderate','little','none'],
    'alfa_scientist': [56, 162, 198, 211],
    'beta_scientist': [56, 223, 243, 239],
    'not_scientist': [109, 164, 74, 28]
})
dfspirituality.head()

  sense_of_spirituality  alfa_scientist  beta_scientist  not_scientist
0                   lot              56              56            109
1              moderate             162             223            164
2                little             198             243             74
3                  none             211             239             28

In [ ]:
# Stap 1
# H₀ => geen verband tussen opleiding en spiritualiteit
# H₁ => wel verband

# Stap 2
alpha = 0.05

# Stap 3
# => chi²

# Stap 4
# => p + g

dfspirituality = dfspirituality.drop('sense_of_spirituality', axis=1)
chi2, p, dof, expected = stats.chi2_contingency(dfspirituality)
g = stats.chi2.isf(alpha, df=dof)  # Critical value

print("Significance level  ⍺ = %.2f" % alpha)
print("Sample size         n = %d" % n)
print("k = %d; df = %d" % (k, dof))
print("Chi-squared        χ² = %.4f" % chi2)
print("Critical value      g = %.4f" % g)
print("p-value             p = %.4f" % p)

# Stap 5
# p << alpha => Wel verband
# chi2 >> g  |

Significance level  ⍺ = 0.05
Sample size         n = 1361
k = 4; df = 6
Chi-squared        χ² = 213.2122
Critical value      g = 12.5916
p-value             p = 0.0000

## Exercise 3

In an experiment, 150 patients were divided into three groups of 45, 45 and 60 patients each. Two groups were given a new drug in different doses and the third group was given a placebo. The way the patients felt after using the drug are shown in the data frame below. Is there evidence at the 5% significance level that there is a difference in the condition between the three groups of patients?

In [11]:
dfexperiment = pd.DataFrame(data={
    'state': ['better', 'equal', 'worse'],
    'placebo': [16, 20, 9],
    'half_dosis': [17, 18, 10],
    'full_dosis': [26, 20, 14]
}).set_index('state')
dfexperiment.head()

        placebo  half_dosis  full_dosis
state
better       16          17          26
equal        20          18          20
worse         9          10          14

In [ ]:
# Stap 1
# H₀ => geen verband tussen dosis en state
# H₁ => wel verband

# Stap 2
alpha = 0.05

# Stap 3
# => chi²

# Stap 4
# => p + g

chi2, p, dof, expected = stats.chi2_contingency(dfexperiment)
g = stats.chi2.isf(alpha, df=dof)  # Critical value

print("Significance level  ⍺ = %.2f" % alpha)
print("Sample size         n = %d" % n)
print("k = %d; df = %d" % (k, dof))
print("Chi-squared        χ² = %.4f" % chi2)
print("Critical value      g = %.4f" % g)
print("p-value             p = %.4f" % p)

# Stap 5
# p >> alpha => Geen verband, niet voldoende aanwijzing om H₀ te verwerpen
# chi2 << g  |

Significance level  ⍺ = 0.05
Sample size         n = 1361
k = 4; df = 4
Chi-squared        χ² = 1.4169
Critical value      g = 9.4877
p-value             p = 0.8412